services:
  - type: web
    name: waha-prm
    runtime: docker
    plan: standard
    autoDeploy: true
    healthCheckPath: /ping
    envVars:
      - key: WHATSAPP_DEFAULT_ENGINE
        value: WEBJS
      - key: WAHA_API_KEY_EXCLUDE_PATH
        value: ping,health
      - key: WHATSAPP_API_KEY_EXCLUDE_PATH
        value: ping,health
      - key: WAHA_API_KEY
        sync: false
      - key: WAHA_DASHBOARD_USERNAME
        sync: false
      - key: WAHA_DASHBOARD_PASSWORD
        sync: false
